baseURL = 'https://minidump.net/'
languageCode = 'en-us'
title = 'minidump.net'
theme = 'tranquilpeak'
defaultContentLanguage = "en-us"

[params]
  sidebarBehavior = 2
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "images/code.png"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
  dateFormat = "January 02 2006"

[params.comment.utterances]
  enable = true
  repo = 'kevingosse/kevingosse.github.io'

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[author]
  name = "Kevin Gosse"
  twitter = "kookiz"
  picture = "images/profile.png"
  bio = "Kevin Gosse has been using Microsoft .NET technologies for more than 15 years, across client, server, and mobile applications. Passionate about debugging. He is Microsoft MVP and is currently employed at Datadog, where he works on the performance of the .NET APM."

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-bookmark\" aria-hidden=\"true\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-tags\" aria-hidden=\"true\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-archive\" aria-hidden=\"true\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-question\" aria-hidden=\"true\"></i>"
  url = "/#about"

[[menu.misc]]
  weight = 1
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-twitter\" aria-hidden=\"true\"></i>"
  url = "https://twitter.com/kookiz"

[[menu.misc]]
  weight = 2
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = "https://github.com/kevingosse"

[[menu.misc]]
  weight = 3
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-rss\" aria-hidden=\"true\"></i>"
  url = "/index.xml"

[[menu.misc]]
  weight = 4
  identifier = "buymeacoffee"
  name = "Buy me a coffee"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-coffee\" aria-hidden=\"true\"></i>"
  url = "https://www.buymeacoffee.com/kevingosse"

[[params.sharingOptions]]
    name = "Twitter"
    icon = "fab fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [[params.sharingOptions]]
    name = "Linkedin"
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/feed/?shareActive=true&text=%s"

  [[params.sharingOptions]]
    name = "Reddit"
    icon = "fab fa-reddit"
    url = "https://www.reddit.com/submit?url=%s"

  [[params.sharingOptions]]
    name = "Hacker News"
    icon = "fab fa-hacker-news"
    url = "https://news.ycombinator.com/submitlink?u=%s"